# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8cc03b54a63e50cd80301bc6d3283e6746d0503d8768092cb8d63c16e903fc2316967051499e4e13d60ba53dacd4c6dd3ea8c913eb434ba14ecadb2c10d92b9b

test:
  secret_key_base: cb1cf1d38cb57c193ec0354573dd377fdade6f63549f23c078884dc542e38e0bcf3d0719a4168a317c712f083c2b01896d8d4381e9d18a1fd79d86288abee65f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
